server:
  port: 8200

consumer:
  reactive: false

spring:
  cloud:
    stream:
      function:
        definition: retryService;retryTopic1;retryTopic2;retryTopic3;retryTopic4;dlqListener

      # Kafka binder configuration
      default-binder: kafka
      kafka:
        binder:
          required-acks: all
          auto-alter-topics: true
          auto-add-partitions: true
          min-partition-count: 4
          producer-properties:
            batch.size: 1000
            linger.ms: 5
            enable.idempotence: true
          transaction:
            transaction-id-prefix: retry-${INSTANCE_ID:1}
            producer:
              partition-count: 4

      # Default binding configuration
      default:
        producer:
          header-mode: headers
          use-native-encoding: true
        consumer:
          use-native-decoding: true
          concurrency: 4
          partitioned: true

      kafka.bindings:
        retryTopic1-in-0:
          consumer:
            configuration:
              isolation.level: read_committed

        retryTopic2-in-0:
          consumer:
            configuration:
              isolation.level: read_committed

        retryTopic3-in-0:
          consumer:
            configuration:
              isolation.level: read_committed

        retryTopic4-in-0:
          consumer:
            configuration:
              isolation.level: read_committed

      bindings:
        # Retry Service Topic - We could listen to multiple topics and verify
        # that the reply-topic is allowed to send back to the same topic
        retryService-in-0:
          group: retry-internal
          destination: retry.topic
        retryService-out-0.destination: ${retry.dead-letter-topic}

        # Retry Topic 1
        retryTopic1-in-0:
          group: retry-internal
          destination: ${retry.delay-topics[0].topic}
          consumer:
            batch-mode: false
        retryTopic1-out-0.destination: ${retry.dead-letter-topic}

        # Retry Topic 2
        retryTopic2-in-0:
          group: retry-internal
          destination: ${retry.delay-topics[1].topic}
          consumer:
            batch-mode: false
        retryTopic2-out-0.destination: ${retry.dead-letter-topic}

        # Retry Topic 3
        retryTopic3-in-0:
          group: retry-internal
          destination: ${retry.delay-topics[2].topic}
          consumer:
            batch-mode: false
        retryTopic3-out-0.destination: ${retry.dead-letter-topic}

        # Retry Topic 4
        retryTopic4-in-0:
          group: retry-group
          destination: ${retry.delay-topics[3].topic}
          consumer:
            batch-mode: false
        retryTopic4-out-0.destination: ${retry.dead-letter-topic}

        # Dead Letter Queue
        dlqListener-in-0:
          group: retry-group
          destination: ${retry.dead-letter-topic}
          consumer.concurrency: 1

retry:
  jitter: 100ms
  dead-letter-topic: retry.dlq
  delay-topics:
    - delay: 1s
      topic: retry.internal.delay1
    - delay: 3s
      topic: retry.internal.delay2
    - delay: 7s
      topic: retry.internal.delay3
    - delay: 17s
      topic: retry.internal.delay4

logging:
  level:
    org.springframework: WARN
    org.springframework.cloud.stream: WARN
    org.apache.kafka: WARN
